// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbEwgHhjW7AK-Fpu2lN7nMnOdhQHAxiU',
    appId: '1:406351109765:web:b2534be77a56d54ac293ec',
    messagingSenderId: '406351109765',
    projectId: 'toryumon-94f6c',
    authDomain: 'toryumon-94f6c.firebaseapp.com',
    storageBucket: 'toryumon-94f6c.appspot.com',
    measurementId: 'G-TM63TEXKGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqH8pzF3vbnQXmEN-WGrARHmtGhDZHO3A',
    appId: '1:406351109765:android:284ad0ff8ed8ce07c293ec',
    messagingSenderId: '406351109765',
    projectId: 'toryumon-94f6c',
    storageBucket: 'toryumon-94f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkFXERC5zuLIHncUdMWPO4JBP8FuTz_S4',
    appId: '1:406351109765:ios:edc67dfa07d64cb7c293ec',
    messagingSenderId: '406351109765',
    projectId: 'toryumon-94f6c',
    storageBucket: 'toryumon-94f6c.appspot.com',
    iosBundleId: 'com.example.toryumonSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkFXERC5zuLIHncUdMWPO4JBP8FuTz_S4',
    appId: '1:406351109765:ios:edc67dfa07d64cb7c293ec',
    messagingSenderId: '406351109765',
    projectId: 'toryumon-94f6c',
    storageBucket: 'toryumon-94f6c.appspot.com',
    iosBundleId: 'com.example.toryumonSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMbEwgHhjW7AK-Fpu2lN7nMnOdhQHAxiU',
    appId: '1:406351109765:web:2136d2c13ca38548c293ec',
    messagingSenderId: '406351109765',
    projectId: 'toryumon-94f6c',
    authDomain: 'toryumon-94f6c.firebaseapp.com',
    storageBucket: 'toryumon-94f6c.appspot.com',
    measurementId: 'G-QJP0QK84L1',
  );
}
